### ISSUE TITLE
Make it valid to pass `accelerator_options` without `ipu_options_file`

### ISSUE THREAD

**Issue by callumm-graphcore** [datamol-io/graphium#246]
This would make it possible to use pipelining (in the current implementation) while using the default IPU options file

Current error message, which we want to avoid:

```
[16:47:56.187] [poptorch::python] [critical] TypeError: expected str, bytes or os.PathLike object, not NoneType

Traceback (most recent call last):
  File "main_run_multitask.py", line 93, in <module>
    main(cfg)
  File "main_run_multitask.py", line 47, in main
    datamodule = load_datamodule(cfg)
  File "/localdata/callumm/valence/goli/goli/config/_loader.py", line 148, in load_datamodule
    ipu_training_config_file, ipu_inference_config_overrides_file = _get_ipu_options_files(config)
  File "/localdata/callumm/valence/goli/goli/config/_loader.py", line 95, in _get_ipu_options_files
    if pathlib.Path(ipu_training_config_path).is_file():
  File "/usr/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by DomInvivo** [comment]
There are no longer `ipu_options_file`, it's now handled in the `accelerator` part of the YAML configs
