### ISSUE TITLE
Task norms error: `TypeError: 'NoneType' object is not subscriptable`

### ISSUE THREAD

**Issue by callumm-graphcore** [datamol-io/graphium#318]
````
Traceback (most recent call last):
  File "run_gpspp.py", line 131, in <module>
    main(cfg)
  File "run_gpspp.py", line 62, in main
    predictor = load_predictor(cfg, model_class, model_kwargs, metrics)
  File "/localdata/callumm/valence/g7/goli/goli/config/_loader.py", line 328, in load_predictor
    predictor = predictor_class(
  File "/localdata/callumm/valence/g7/goli/goli/ipu/ipu_wrapper.py", line 110, in __init__
    super().__init__(*args, **kwargs)
  File "/localdata/callumm/valence/g7/goli/goli/trainer/predictor.py", line 128, in __init__
    self.task_epoch_summary = TaskSummaries(
  File "/localdata/callumm/valence/g7/goli/goli/trainer/predictor_summaries.py", line 378, in __init__
    task_specific_norm=task_norms[task],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by DomInvivo** [comment]
Fixed somewhere I believe. It happened because the `task_norms` were not initialized correctly when loading from RAM instead of Disk
