### ISSUE TITLE
error with  graphium-train finetuning

### ISSUE THREAD

**Issue by mohamedelabbas1996** [datamol-io/graphium#439]
I am getting this error when running `graphium-train +finetuning=admet`

```
Error executing job with overrides: ['+finetuning=admet']
Traceback (most recent call last):
  File "/content/graphium/graphium/cli/train_finetune.py", line 31, in cli
    run_training_finetuning(cfg)
  File "/content/graphium/graphium/cli/train_finetune.py", line 106, in run_training_finetuning
    trainer.fit(model=predictor, datamodule=datamodule)
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 376, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 293, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/root/miniconda3/envs/graphium1/lib/python3.8/site-packages/lightning/pytorch/strategies/strategy.py", line 393, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/content/graphium/graphium/trainer/predictor.py", line 537, in validation_step
    return self._general_step(batch=batch, step_name="val", to_cpu=to_cpu)
  File "/content/graphium/graphium/trainer/predictor.py", line 305, in _general_step
    preds = self.forward(batch)  # The dictionary of predictions
  File "/content/graphium/graphium/trainer/predictor.py", line 190, in forward
    out = self.model.forward(feats)
  File "/content/graphium/graphium/finetuning/finetuning_architecture.py", line 133, in forward
    g = self.finetuning_head.forward(g)
  File "/content/graphium/graphium/finetuning/finetuning_architecture.py", line 321, in forward
    if isinstance(g, Union[torch.Tensor, Batch]):
  File "/root/miniconda3/envs/graphium1/lib/python3.8/typing.py", line 766, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/root/miniconda3/envs/graphium1/lib/python3.8/typing.py", line 774, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks

```
Environment:
OS : Ubuntu 22.04.2 LTS
Python version : 3.8.0

**Comment by cwognum** [comment]
Hey @mohamedelabbas1996, 

Good catch! It appears some Python syntax slipped through which is only supported in `python >=3.10` (see [PEP 604](https://peps.python.org/pep-0604/#isinstance-and-issubclass) for more information), whereas our env file specifies support for `>=3.8`. I opened #442 to fix this issue and hope it will be resolved soon! This PR also makes sure all our test cases are run on more versions of Python, so that we catch issues like these earlier next time. 

Thank you for your interest in Graphium and your contribution! 🙏
